Add support for repo owner parameters Dependency versions bump

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,26 +3,25 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: ""
 app:
   envs:
-  - API_TOKEN: $API_TOKEN
-  - BITRISE_APP_SLUG: $BITRISE_APP_SLUG
-  - WORKFLOW_ID: $WORKFLOW_ID
-  - EXPORTED_ENVIRONMENT: $EXPORTED_ENVIRONMENT
-  - BITRISE_STEP_ID: trigger-bitrise-workflow
-  - BITRISE_STEP_VERSION: "0.0.6"
-  - BITRISE_STEP_GIT_CLONE_URL: https://github.com/DroidsOnRoids/bitrise-step-trigger-bitrise-workflow.git
-  - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
-  - BITRISE_GO_PACKAGES: github.com/DroidsOnRoids/bitrise-step-trigger-bitrise-workflow
-    opts:
-      is_expand: false
+    - API_TOKEN: $API_TOKEN
+    - BITRISE_APP_SLUG: $BITRISE_APP_SLUG
+    - WORKFLOW_ID: $WORKFLOW_ID
+    - EXPORTED_ENVIRONMENT: $EXPORTED_ENVIRONMENT
+    - BITRISE_STEP_ID: trigger-bitrise-workflow
+    - BITRISE_STEP_GIT_CLONE_URL: https://github.com/DroidsOnRoids/bitrise-step-trigger-bitrise-workflow.git
+    - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
+    - BITRISE_GO_PACKAGES: github.com/DroidsOnRoids/bitrise-step-trigger-bitrise-workflow
+      opts:
+        is_expand: false
 workflows:
   audit-this-step:
     steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            stepman audit --step-yml ./step.yml
+      - script:
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -ex
+                stepman audit --step-yml ./step.yml
   share-this-step:
     description: |-
       If this is the first time you try to share a Step you should
@@ -37,67 +36,62 @@ workflows:
       in the `.bitrise.secrets.yml` file, or here in the `envs` section,
       as the value of the `MY_STEPLIB_REPO_FORK_GIT_URL` environment.
 
-      You're now ready to share this Step, just make sure that
-      the `BITRISE_STEP_ID` and `BITRISE_STEP_VERSION`
-      environments are set to the desired values!
-
       To share this Step into a StepLib you can just run: $ bitrise run share-this-step
 
       Once it finishes the only thing left is to actually create a Pull Request,
       the way described in the guide printed at the end of the process.
     before_run:
-    - audit-this-step
+      - audit-this-step
     envs:
-    - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
-    - BITRISE_STEP_ID: $BITRISE_STEP_ID
-    - BITRISE_STEP_VERSION: $BITRISE_STEP_VERSION
-    - BITRISE_STEP_GIT_CLONE_URL: $BITRISE_STEP_GIT_CLONE_URL
+      - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
+      - BITRISE_STEP_ID: $BITRISE_STEP_ID
+      - BITRISE_STEP_GIT_CLONE_URL: $BITRISE_STEP_GIT_CLONE_URL
     steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            bitrise share start -c "${MY_STEPLIB_REPO_FORK_GIT_URL}"
-            bitrise share create --stepid "${BITRISE_STEP_ID}" --tag "${BITRISE_STEP_VERSION}" --git "${BITRISE_STEP_GIT_CLONE_URL}"
-            bitrise share finish
+      - script:
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -ex
+                bitrise share start -c "${MY_STEPLIB_REPO_FORK_GIT_URL}"
+                bitrise share create --stepid "${BITRISE_STEP_ID}" --tag "$(git describe --tags --exact-match)" --git "${BITRISE_STEP_GIT_CLONE_URL}"
+                bitrise share finish
   test:
     steps:
-    - errcheck: {}
-    - golint: {}
-    - go-test: {}
-    - change-workdir:
-        title: Switch working dir to test / _tmp dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
-        run_if: "true"
-        inputs:
-        - path: ./_tmp
-        - is_create_path: true
-    - path::./:
-        title: Step Test
-        run_if: '{{getenv "BITRISE_APP_SLUG" | ne ""}}'
-        inputs:
-        - workflow_id: $WORKFLOW_ID
-        - api_token: $API_TOKEN
-        - exported_environment_variable_names: $EXPORTED_ENVIRONMENT
-    - script:
-        title: Step Test skip info
-        run_if: '{{enveq "BITRISE_APP_SLUG" ""}}'
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            echo "Step test skipped due to missing App slug"
-    - script:
-        title: Output veriables demo
-        inputs:
-        - content: |
-            #!/usr/bin/env bash
-            echo "Outputs generated by this step:"
-            echo "TRIGGERED_BUILD_SLUG: $TRIGGERED_BUILD_SLUG"
-            echo "TRIGGERED_BUILD_NUMBER: $TRIGGERED_BUILD_NUMBER"
-            echo "TRIGGERED_BUILD_URL: $TRIGGERED_BUILD_URL"
-            echo "TRIGGERED_WORKFLOW_ID: $TRIGGERED_WORKFLOW_ID"
+      - errcheck: {}
+      - golint: {}
+      - go-test: {}
+      - change-workdir:
+          title: Switch working dir to test / _tmp dir
+          description: |-
+            To prevent step testing issues, like referencing relative
+            files with just './some-file' in the step's code, which would
+            work for testing the step from this directory directly
+            but would break if the step is included in another `bitrise.yml`.
+          run_if: "true"
+          inputs:
+            - path: ./_tmp
+            - is_create_path: true
+      - path::./:
+          title: Step Test
+          run_if: '{{getenv "BITRISE_APP_SLUG" | ne ""}}'
+          inputs:
+            - workflow_id: $WORKFLOW_ID
+            - api_token: $API_TOKEN
+            - exported_environment_variable_names: $EXPORTED_ENVIRONMENT
+      - script:
+          title: Step Test skip info
+          run_if: '{{enveq "BITRISE_APP_SLUG" ""}}'
+          inputs:
+            - content: |-
+                #!/usr/bin/env bash
+                echo "Step test skipped due to missing App slug"
+      - script:
+          title: Output veriables demo
+          inputs:
+            - content: |
+                #!/usr/bin/env bash
+                echo "Outputs generated by this step:"
+                echo "TRIGGERED_BUILD_SLUG: $TRIGGERED_BUILD_SLUG"
+                echo "TRIGGERED_BUILD_NUMBER: $TRIGGERED_BUILD_NUMBER"
+                echo "TRIGGERED_BUILD_URL: $TRIGGERED_BUILD_URL"
+                echo "TRIGGERED_WORKFLOW_ID: $TRIGGERED_WORKFLOW_ID"
